export const en = {
  translation: {
    onboardingTitle1: 'Feel inspired, and keep meowtivated',
    onboardingTitle2: 'Purr-sue your dreams with unwavering spirit',
    onboardingTitle3: 'Seize every meowment, for success is near',
    onboardingButton: 'Get Started',
    search: 'Search',
    favoritesEmptyListDescription:
      'No favorite quotes yet. Paw-lease save some purr-fect inspiration!',
    favorites: 'Favorites',
    delete: 'Delete',
    cancel: 'Cancel',
    settings: 'Settings',
    appearance: 'Appearance',
    language: 'Language',
    theme: 'Theme',
    soon: 'Soon',
    data: 'Data',
    clearData: 'Clear Data',
    about: 'About',
    version: 'Version',
    rateApp: 'Rate App',
    contact: 'Contact',
    clearDataConfirm:
      'Are you sure? This will delete all your favorites and reset daily quotes.',
    success: 'Success',
    dataCleared: 'Data has been cleared successfully',
    confirm: 'Confirm',
    buyThemeTitle: '🐾 New theme 🐾',
    buyThemeMessage: 'Ready to unleash this meow-tastic theme?',
    applyThemeTitle: 'Apply Theme?',
    applyThemeMessage: 'Do you want to apply this theme now?',
    quotes: [
      '"Start each day with a purrpose, and end it with a purr of satisfaction."',
      '"The journey to your dreams is like a cat\'s nap—quiet, peaceful, and filled with unexpected leaps."',
      '"Your inner tiger is just waiting to pounce on your goals. Let it roar today!"',
      '"Life is like a ball of yarn, full of twists and turns. Unravel it with curiosity and grace."',
      '"Chase your dreams like a cat chasing a laser—focused, playful, and unstoppable."',
      '"Every challenge is a new scratching post for sharpening your skills."',
      '"Stay pawsitive, even when the world seems a little hiss-terical."',
      '"In the game of life, be the cat that always lands on its feet."',
      '"Meowtivation is the key to unlocking the catnip of success."',
      '"Curl up with your dreams, but don\'t forget to leap towards them too."',
      '"Pounce on every opportunity, and don’t let the mouse of doubt escape."',
      '"Your whiskers of wisdom grow with every experience—use them to navigate your path."',
      '"Be the curious cat that never stops exploring new horizons."',
      '"Even on the longest days, remember that every sunset brings the promise of a new dawn."',
      '"A cat\'s heart is full of determination and a dash of mischief—use both to your advantage."',
      '"Balance your goals like a cat balancing on a fence, with grace and determination."',
      '"Don\'t be afraid to show your claws when you\'re fighting for your dreams."',
      '"Let your meow be heard in the world of whispers."',
      '"Life is a series of catnaps and adventures—embrace them both."',
      '"Every day is a new chance to scratch out your destiny with creativity and confidence."',
      '"In every whisker, find the courage to chase your dreams."',
      '"Let your inner tiger meow and pounce on opportunities."',
      '"Life\'s a climb, but every step is a graceful leap."',
      '"Stay curious, like a cat chasing a beam of light."',
      '"Stretch out your paws and reach for the stars."',
      '"Even a catnap can recharge your dreams."',
      '"When life gets tough, purr through the challenges."',
      '"Every meow is a reminder to express yourself."',
      '"Keep your claws sharp, your goals sharper."',
      '"Like a cat, land on your feet no matter the fall."',
      '"Pounce on every opportunity with feline grace."',
      '"Find joy in the simple things, like a cat with a sunbeam."',
      '"The path to success is a series of well-timed leaps."',
      '"In the quiet moments, let your ideas take root."',
      '"With each purr, let go of what doesn\'t serve you."',
      '"A cat’s grace is matched only by its determination."',
      '"Chase your dreams like a cat chasing a laser."',
      '"Your potential is as vast as a cat\'s curiosity."',
      '"Let your whiskers guide you to new adventures."',
      '"Every day is a chance to meow, stretch, and grow."',
      '"Every challenge is just a mouse to be caught, so don\'t be afraid to pounce."',
      '"A cat never rushes, but always gets where it’s going with elegance and purpose."',
      '"Let your spirit soar like a cat chasing after a butterfly on a summer day."',
      '"In the face of adversity, remember, even a small kitten has the heart of a lion."',
      '"Purr with contentment, but never stop reaching for that next dream."',
      '"The world is your playground; leap over obstacles like a cat chasing after a ball of yarn."',
      '"Even the longest nap ends with a stretch and a new adventure to explore."',
      '"Find your sunbeam, and bask in the warmth of your achievements."',
      '"Each day is a new chance to sharpen your claws and refine your goals."',
      '"No matter how high the climb, remember that even the highest tree starts at the ground."',
      '"A cat\'s grace isn\'t just in its steps, but in its ability to land on its feet, every time."',
      '"Pursue your dreams with the same determination a cat uses to catch its prey."',
      '"In the quiet of the night, let your dreams roam free like a cat on the prowl."',
      '"Success is just a series of well-planned pounces away."',
      '"The world is filled with endless nooks and crannies, all waiting for you to explore."',
      '"Like a cat, let curiosity be the fuel that drives your journey."',
      '"Never underestimate the power of a well-timed purr; it can open doors to new opportunities."',
      '"Each day offers a new adventure, so leap into it with all the grace of a feline."',
      '"In the face of failure, remember: even a cat doesn’t always catch the mouse on the first try."',
      '"Every whisker twitch is a reminder to be aware of your surroundings and seize opportunities."',
      '"The journey to success is like a cat’s hunt: patient, calculated, and always on point."',
      '"Don\'t just climb trees, aim to reach the very top branch where the view is the best."',
      '"The smallest steps can lead to the biggest changes, just as a kitten grows into a mighty cat."',
      '"Let each day begin with a stretch, a purr, and a renewed sense of purpose."',
      '"Your goals may be lofty, but with feline determination, no tree is too tall to climb."',
      '"In every meow, there’s a story waiting to be told, so make yours worth listening to."',
      '"Even on lazy days, remember that rest is just preparation for your next big leap."',
      '"A cat doesn’t need permission to be majestic, and neither do you."',
      '"With each new dawn, remember that you have nine lives to make your dreams come true."',
      '"Even when the world seems chaotic, find your calm center and let it guide you."',
      '"A soft purr can turn the harshest of days into something beautiful."',
      '"The road to your dreams may be long, but every step is a leap toward your destiny."',
      '"Never stop playing, for in play, we find the true meaning of joy and creativity."',
      '"Life is better with a little purr-suasion; use your charm to open new doors."',
      '"No goal is too big if you approach it with the patience and precision of a cat."',
      '"Even in the darkest night, the eyes of a cat see opportunities where others see none."',
      '"With each graceful leap, remember that you\'re one step closer to catching your dreams."',
      '"Let your inner feline guide you to the places where your heart truly belongs."',
      '"Every cat nap is a reminder that rest is just as important as action."',
      '"Embrace your independence, but never forget the power of connection and community."',
      '"Like a cat in a sunbeam, find the light in every situation and bask in it."',
      '"Don’t just chase your dreams; hunt them down with the precision of a cat stalking its prey."',
      '"Let your curiosity lead you to places you\'ve never imagined, just like a cat exploring a new world."',
      '"With each purr, let go of the past and welcome the future with open paws."',
      '"Even the smallest kitten has the potential to become the king of the jungle."',
      '"Find your balance, and move through life with the grace of a feline."',
      '"Like a cat, be both fierce and gentle; know when to pounce and when to purr."',
      '"Each day is a new chance to find your rhythm and dance to the beat of your own drum."',
      '"Every challenge is a new opportunity to show your inner strength and resilience."',
      '"A cat\'s curiosity never gets the better of it; let your curiosity guide your path to success."',
      '"Each leap you take is a step closer to reaching your highest aspirations."',
      '"Embrace the playful side of life, for in play, we discover the essence of joy."',
      '"Just as a cat always lands on its feet, you too will find your way through any challenge."',
      '"Your dreams are as vast as the sky; let them soar as high as a cat leaps after a bird."',
      '"Let each purr be a reminder that even the smallest gestures can bring the greatest rewards."',
      '"Every moment of patience is a step toward achieving greatness, just like a cat stalking its prey."',
      '"Like a cat waiting for the perfect moment to pounce, sometimes the best results come with time."',
      '"Embrace your journey with the same elegance and grace that a cat displays in its every move."',
      '"Let your dreams be as limitless as a cat’s imagination as it chases after the unseen."',
      '"Each day is a chance to add another page to the story of your success, so make it count."',
      '"With every gentle purr, let go of doubts and embrace the certainty of your potential."',
      '"A cat\'s playful nature reminds us that success can be as much about enjoying the journey as reaching the goal."',
      '"Find your purpose with the same focus a cat uses to follow a laser pointer; never lose sight of it."',
      '"Every step you take is a dance with destiny; let it be as graceful as a cat\'s paw."',
      '"Celebrate each small victory as a cat does with a playful leap; it’s a step toward greater success."',
      '"Let your spirit be as unbreakable as a cat\'s resolve; with determination, anything is possible."',
      '"Each day is a new adventure, so approach it with the same curiosity a cat has for its surroundings."',
      '"Like a cat curled up in the sun, find your moments of peace amidst the hustle and bustle."',
      '"Don’t just dream of success; let it become your reality with the persistence of a cat on a hunt."',
      '"Every day is an opportunity to explore new paths and climb new heights, just as a cat explores its world."',
      '"With each graceful move, remember that you are capable of achieving great things, just like a cat."',
      '"Embrace your journey with the same confidence a cat shows when it leaps from one rooftop to another."',
      '"Every moment of rest is a preparation for the next leap toward your dreams, just like a cat’s pause before a jump."',
      '"Let your goals be as high as a cat’s dreams as it gazes out of a window; aim for the stars."',
      '"In every leap you take, find the joy and excitement that a cat feels when chasing after its favorite toy."',
      '"Let the warmth of your achievements be like a cat’s sunny spot; bask in it and enjoy every moment."',
      '"Embrace each challenge with the same determination a cat shows when chasing a laser pointer."',
      '"Each day offers a fresh start; approach it with the curiosity and eagerness of a kitten exploring a new toy."',
      '"Let each achievement be a reminder that you are capable of more, just as a cat grows stronger with each play."',
      '"Every new experience is an opportunity to grow, just like a cat learns and adapts to its surroundings."',
      '"Celebrate your progress with the same joy a cat shows when it catches a new toy or discovers a new nook."',
      '"Find your rhythm and move with the grace and confidence of a cat on a mission."',
      '"Each day is a new opportunity to chase after your dreams with the same enthusiasm a cat has for its favorite game."',
      '"Let your goals shine as brightly as a cat’s eyes in the dark; with focus, you can achieve anything."',
      '"Embrace your inner strength with the same poise and determination a cat shows when facing a new challenge."',
      '"Every step forward is a leap toward your dreams; let it be as bold and purposeful as a cat\'s pounce."',
      '"Celebrate each success, no matter how small, with the same joy and enthusiasm a cat has for its favorite treat."',
      '"Let your journey be as adventurous and exciting as a cat’s playful exploration of its world."',
      '"Every challenge you face is like a mouse waiting to be caught—so leap forward with courage and determination."',
      '"A cat may not rush, but it always makes it to its destination with a mix of grace and purpose—take this lesson to heart in your journey."',
      '"Imagine your spirit soaring like a cat chasing a butterfly in the warm summer breeze; let your dreams take flight."',
      '"Even in the face of the toughest obstacles, remember that even the tiniest kitten has the heart and bravery of a lion."',
      '"Purr contentedly for your achievements, but keep reaching for your next big dream with the same tenacity."',
      '"Life is your playground—navigate obstacles with the playful agility of a cat leaping after a ball of yarn."',
      '"Even the longest and laziest naps end with a stretch and a renewed sense of adventure; make sure to rejuvenate and keep exploring."',
      '"Find your personal ray of sunshine and bask in the warmth of your accomplishments, just like a cat enjoys a sunny spot."',
      '"Each new day brings a fresh opportunity to sharpen your claws and refine your goals—embrace the process with enthusiasm."',
      '"No matter how high the climb seems, remember that even the tallest tree started from the ground; your efforts will lead you upward."',
      '"A cat’s grace is not just in its steps but in its ability to land on its feet, regardless of the fall; learn from its resilience."',
      '"Chase your dreams with the same determination and focus a cat uses when it’s on the hunt for its prey—be relentless."',
      '"In the quiet of the night, let your dreams wander as freely as a cat on the prowl, exploring every possibility."',
      '"Success is like a series of well-planned leaps; each step you take brings you closer to achieving your goals."',
      '"The world is filled with hidden nooks and crannies waiting to be discovered—embrace your curiosity and explore them all."',
      '"Let curiosity fuel your journey as it does for a cat exploring new territories; let it lead you to wonderful discoveries."',
      '"Never underestimate the power of a well-timed purr; it can turn challenges into opportunities and open doors you didn’t see before."',
      '"Every day offers a new adventure, so dive into it with the same grace and eagerness a feline shows while exploring its world."',
      '"When facing failure, remember: even a cat doesn’t catch its prey on the first attempt; persistence is key."',
      '"Every twitch of a cat’s whiskers is a reminder to stay alert and seize the opportunities around you with readiness and anticipation."',
      '"The path to success is like a cat’s hunt: patient, calculated, and executed with precision—stay focused and determined."',
      '"Don’t just climb trees; aim for the highest branches where the view is the most magnificent—stretch your ambitions."',
      '"The smallest steps can lead to the most significant changes; like a kitten growing into a majestic cat, embrace your growth journey."',
      '"Begin each day with a stretch, a purr, and a renewed sense of purpose—ready yourself for what lies ahead."',
      '"Your goals may seem lofty, but with feline determination, no tree is too tall to conquer—reach for the stars."',
      '"Every meow tells a story waiting to be shared; make sure your story is one of perseverance and success."',
      '"Even on the laziest of days, remember that rest is simply preparation for your next big leap forward—recharge and keep moving."',
      '"A cat doesn’t need permission to be majestic, and neither do you—embrace your inherent greatness and shine."',
      '"With each new dawn, remember you have multiple chances to achieve your dreams—like having nine lives, make each one count."',
      '"Even when the world around you seems chaotic, find your center of calm and let it guide you through the storm."',
      '"A gentle purr can transform the toughest days into something beautiful and soothing; let it bring you peace."',
      '"The journey to your dreams may be long, but each step is a leap towards your goals; remain steadfast and persistent."',
      '"Never stop playing, as in play we uncover the true essence of joy and creativity—keep the spirit of play alive in your endeavors."',
      '"Life is better with a touch of feline charm; use your unique qualities to open new doors and opportunities."',
      '"No goal is too big if approached with the patience and precision of a cat; stay methodical and focused."',
      '"Even in the darkest of nights, a cat’s eyes find opportunities where others see only shadows; let your vision guide you."',
      '"With every graceful leap, remember you’re advancing towards your dreams; keep moving with purpose and confidence."',
      '"Let your inner feline guide you to where your heart truly belongs—follow your instincts and passion."',
      '"Every catnap serves as a reminder that rest is essential for the next leap towards your dreams; balance action with relaxation."',
      '"Embrace your independence, but also recognize the strength in community and connection—nurture both."',
      '"Like a cat basking in a sunbeam, find and enjoy the light in every situation; let it warm and inspire you."',
      '"Don’t just chase your dreams—capture them with the same precision and dedication a cat shows when stalking its prey."',
      '"Allow your curiosity to lead you to new horizons, just as a cat explores a new world with wonder and excitement."',
      '"With each purr, release the past and embrace the future with open paws—move forward with optimism and hope."',
      '"Even the smallest kitten has the potential to become a majestic creature—never underestimate your own potential."',
      '"Find your balance and navigate through life with the same grace a feline displays—move with purpose and poise."',
      '"Like a cat, be both fierce and gentle; understand when to act decisively and when to show patience and compassion."',
      '"Every day is a new opportunity to find your rhythm and dance to the beat of your own drum—embrace your unique journey."',
      '"Each challenge you face is a new chance to demonstrate your inner strength and resilience; rise to the occasion with confidence."',
      '"A cat’s boundless curiosity never hinders it; let your own curiosity guide your path to success and discovery."',
      '"Every leap you make brings you closer to achieving your highest aspirations; continue to leap with courage and determination."',
      '"Embrace life’s playful side, as in play we find the essence of joy and creativity—never lose your playful spirit."',
      '"Just as a cat always lands on its feet, trust that you too will find your way through any challenge with resilience and adaptability."',
      '"Your dreams are vast as the sky; let them soar as high as a cat leaps after a bird—reach for the stars."',
      '"Let each purr remind you that even the smallest actions can yield great rewards—cherish every moment of progress."',
      '"Every moment of patience is a step toward greatness; like a cat stalking its prey, be patient and persistent in your efforts."',
      '"Sometimes the best results come with time, just as a cat waits for the perfect moment to pounce—trust the process."',
      '"Embrace your journey with the same elegance and grace a cat shows in every movement—move through life with poise."',
      '"Let your dreams be as limitless as a cat’s imagination as it chases the invisible—pursue your passions with boundless energy."',
      '"Each day offers an opportunity to add a new page to your success story—make every moment count and write your own narrative."',
      '"With each gentle purr, release doubts and welcome your potential—embrace your capabilities with confidence."',
      '"A cat’s playful nature reminds us that success is about enjoying the journey as much as reaching the goal—find joy in every step."',
      '"Find your purpose with the same focus a cat has on a laser pointer—never lose sight of your goals and ambitions."',
      '"Each step you take is a dance with destiny; let it be as graceful and deliberate as a cat’s paw movements."',
      '"Celebrate each small victory like a cat with a new toy; it’s a step toward achieving greater success—savor every win."',
      '"Let your spirit be as unwavering as a cat’s determination; with persistence, anything is possible—keep pushing forward."',
      '"Every day is a new adventure—approach it with the curiosity and enthusiasm of a kitten exploring a new toy."',
      '"Like a cat curled up in a sunbeam, find moments of peace amidst life’s hustle—enjoy tranquility when you can."',
      '"Don’t just dream of success—make it a reality with the persistence and focus of a cat on a hunt for its prize."',
      '"Every day presents a chance to explore new paths and reach new heights, just as a cat explores its world with excitement."',
      '"With each graceful movement, remember you are capable of achieving great things—be as poised and purposeful as a cat."',
      '"Embrace your journey with the same confidence a cat shows when leaping from one rooftop to another—fearless and determined."',
      '"Each moment of rest is preparation for the next leap toward your dreams—balance your efforts with moments of rejuvenation."',
      '"Let your goals be as high as a cat’s dreams while gazing out the window; aim for the stars and reach for your aspirations."',
      '"Every challenge you overcome is a testament to your strength and resilience; let your successes inspire and motivate you further."',
      '"Move through life with the same elegance and confidence as a cat moving through its domain—assertive and graceful."',
      '"Just as a cat’s purr can soothe, let your achievements bring you peace and joy—celebrate your progress with pride."',
      '"Every challenge you face is like a mouse waiting to be caught—move forward with bravery and determination, just like a cat on the hunt."',
      '"A cat might not rush, but it always arrives at its destination with a blend of grace and purpose—take that lesson for your journey."',
      '"Imagine your spirit soaring like a cat chasing a butterfly in the warm summer breeze; let your dreams take flight with the same joy."',
      '"Even in the toughest of times, remember that even the smallest kitten has the heart and courage of a lion."',
      '"Purr contentedly with your achievements, but keep pursuing your next big dream with the same tenacity as before."',
      '"Life is your playground—navigate obstacles with the playful agility of a cat leaping after a ball of yarn."',
      '"Even the longest and laziest naps end with a stretch and a renewed sense of adventure; make sure to rejuvenate and keep exploring."',
      '"Find your personal sunbeam and bask in the warmth of your achievements, just like a cat finds a sunny spot to relax."',
      '"Every new day brings a fresh opportunity to sharpen your claws and refine your goals—embrace the process with enthusiasm."',
      '"No matter how high the climb seems, remember that even the tallest tree started from the ground—your efforts will elevate you."',
      '"A cat\'s grace is not only in its steps but in its ability to land on its feet, no matter the fall—learn from its resilience."',
      '"Pursue your dreams with the same determination and focus a cat has when stalking its prey—be relentless in your quest."',
      '"In the quiet of the night, let your dreams roam freely like a cat seeking out new adventures, exploring every possibility."',
      '"Success is like a series of well-planned leaps; each step you take brings you closer to achieving your goals."',
      '"The world is full of hidden nooks and crannies waiting to be discovered—embrace your curiosity and explore everything."',
      '"Let curiosity drive your journey like a cat exploring new territories; let it lead you to wonderful discoveries and new horizons."',
      '"Never underestimate the power of a well-timed purr; it can turn challenges into opportunities and open doors you didn’t see before."',
      '"Every day presents a new adventure, so dive into it with the same grace and excitement as a feline exploring its world."',
      '"When facing setbacks, remember: even a cat doesn’t catch its prey on the first try; persistence is key."',
      '"Each of a cat\'s whisker movements is a reminder to stay alert and seize the opportunities around you with preparation and anticipation."',
      '"The path to success is like a cat’s hunt: patient, calculated, and executed with precision—maintain your focus and determination."',
      '"Don’t just climb trees; aim for the highest branches where the view is the most magnificent—stretch your ambitions."',
      '"Small steps can lead to the most significant changes; like a kitten growing into a majestic cat, embrace your growth journey."',
      '"Start each day with a stretch, a purr, and a renewed sense of purpose—prepare for what’s to come next."',
      '"Your goals may seem high, but with feline determination, no tree is too tall to conquer—reach for the stars."',
      '"Each meow tells a story waiting to be shared; make sure your story is one of perseverance and success."',
      '"Even on the laziest of days, remember that rest is just preparation for your next big leap towards your dreams; recharge and keep moving."',
      '"A cat doesn’t need permission to be majestic, and neither do you—embrace your inherent greatness and shine."',
      '"With each new sunrise, remember you have multiple chances to achieve your dreams—like having nine lives, make each one count."',
      '"Even when the world around you seems chaotic, find your center of calm and let it guide you through the storm."',
      '"A soft purr can turn the hardest days into something beautiful and comforting; let it bring you peace."',
      '"The journey to your dreams may be long, but each step is a leap towards your goals; stay persistent and determined."',
      '"Never stop playing, for in play we discover the true essence of joy and creativity—keep your playful spirit alive in your efforts."',
      '"Life is better with a touch of feline charm; use your unique qualities to open new doors and opportunities."',
      '"No goal is too great if approached with the patience and precision of a cat; keep your methodical focus."',
      '"Even on the darkest nights, a cat’s eyes find opportunities where others only see shadows—let your vision guide you."',
      '"With every graceful leap, remember you’re moving closer to your dreams—keep moving with purpose and confidence."',
      '"Let your inner feline guide you to where your heart truly belongs—follow your instincts and passions."',
      '"Each nap is a reminder that rest is essential for the next leap towards your dreams—balance action with moments of relaxation."',
      '"Embrace your independence, but also recognize the strength in community and connection—cultivate both."',
      '"Like a cat curled up in a sunbeam, find and bask in the light of every situation; let it warm and inspire you."',
      '"Don’t just chase your dreams—capture them with the same precision and dedication as a cat hunting its prey."',
      '"Let curiosity lead you to new horizons, just like a cat exploring its world with wonder and excitement."',
      '"With every purr, release the past and embrace your potential—welcome your abilities with confidence."',
      '"Even the smallest kitten has the potential to grow into a majestic creature—never underestimate your own potential."',
      '"Find your balance and navigate life with the same grace a feline demonstrates—move with purpose and elegance."',
      '"Be both fierce and gentle, like a cat; understand when to act decisively and when to show patience and compassion."',
      '"Every day is a new opportunity to find your rhythm and dance to the beat of your own drum—embrace your unique journey."',
      '"Each challenge you face is a new chance to show your strength and resilience; meet each occasion with confidence."',
      '"A cat’s curiosity never limits it; let your own curiosity guide you to success and discovery."',
      '"Every leap you take brings you closer to achieving your highest aspirations; keep leaping with courage and determination."',
      '"Embrace the playful side of life, for in play we discover joy and creativity—never lose your playful spirit."',
      '"Just as a cat always lands on its feet, trust that you will find your way through any challenge with resilience and adaptability."',
      '"Your dreams are as vast as the sky; let them soar as high as a cat jumps after a bird—reach for the stars."',
      '"Let each purr remind you that even the smallest actions can lead to great rewards—cherish every moment of progress."',
      '"Every moment of patience is a step towards greatness; just like a cat waiting for the perfect moment to pounce—trust the process."',
      '"Sometimes the best results come with time, just as a cat waits for the perfect moment to leap—trust in the process."',
      '"Embrace your journey with the same elegance and grace a cat shows in every movement—move through life with poise."',
      '"Let your dreams be as limitless as a cat’s imagination while chasing the unseen—pursue your passions with boundless energy."',
      '"Every day offers a chance to add a new page to your success story—make every moment count and write your own narrative."',
      '"With every soft purr, release doubts and welcome your potential—embrace your capabilities with confidence."',
      '"A cat’s playful nature reminds us that success is about enjoying the journey as much as reaching the goal—find joy in every step."',
      '"Find your purpose with the same focus a cat has on a laser—never lose sight of your goals and ambitions."',
      '"Every step you take is a dance with destiny; let it be as graceful and deliberate as a cat’s paw movements."',
      '"Celebrate every small victory like a cat with a new toy; it’s a step towards greater success—enjoy each triumph."',
      '"Let your spirit be as unshakable as a cat’s determination; with persistence, everything is possible—keep moving forward."',
      '"Every day is a new adventure—face it with the curiosity and excitement of a kitten discovering a new toy."',
      '"Like a cat basking in a sunbeam, find moments of peace amid the chaos of life—appreciate the tranquility whenever you can."',
      '"Don’t just dream of success—make it a reality with the persistence and focus of a cat in pursuit of its prize."',
      '"Each day presents a chance to explore new paths and reach new heights, just like a cat exploring its world with enthusiasm."',
      '"With every graceful movement, remember you’re capable of achieving great things—be as poised and determined as a cat."',
      '"Embrace your journey with the same confidence a cat shows when jumping from one roof to another—fearless and determined."',
      '"Every moment of rest is preparation for the next leap towards your dreams—balance your efforts with times of rejuvenation."',
      '"Let your goals be as high as a cat’s dreams when looking out the window; aim for the stars and achieve your aspirations."',
      '"Every challenge you overcome is a testament to your strength and resilience; let your successes inspire and motivate you further."',
      '"Move through life with the same grace and confidence a cat shows in its domain—assert and proceed with elegance."',
      '"Just as a cat’s purring can soothe, let your achievements bring peace and joy—celebrate your progress with pride."',
      '"Embrace every challenge with the grace and tenacity of a cat on a mission—your persistence will lead to success."',
      '"In every leap you take, remember that even a cat pauses to gather strength before the next bound—balance your efforts with patience."',
      '"Let your ambitions soar high and true, like a cat stalking its prey with unwavering focus and precision—aim for greatness."',
      '"A day spent pursuing your dreams is like a cat exploring new territories; approach each moment with curiosity and determination."',
      '"Rest and recharge as a cat does, knowing that each pause is a preparation for the next great leap towards your goals."',
      '"Even the smallest effort can lead to monumental results; like a kitten growing into a majestic cat, believe in your potential."',
      '"Start each day with the confidence of a cat striding into a sunbeam—embrace your achievements and face new challenges with the same poise."',
      '"Transform your goals into reality with the same precision as a cat catching a butterfly—be focused and relentless."',
      '"With each hurdle you overcome, remember that even the most agile cat faces obstacles with patience and grace—persist through challenges."',
      '"In your journey towards success, let your curiosity guide you like a cat exploring a new playground—discover and grow with each step."',
      '"No matter how high the climb, know that every effort brings you closer to your dreams—like a cat scaling a tall tree, reach for the sky."',
      '"Let your spirit be as playful and free as a kitten; approach each task with enthusiasm and joy, and you\'ll find success follows."',
      '"Face your dreams with the same bravery as a cat facing its reflection; trust in your abilities and move forward with confidence."',
      '"Even in moments of rest, your progress continues—like a cat nestled in a cozy spot, let relaxation fuel your next move forward."',
      '"Let every challenge be a stepping stone, like a cat leaping from one rooftop to another; each jump brings you closer to your goals."',
      '"Embrace your unique journey with the same pride as a cat displaying its beautiful coat—celebrate each achievement and keep moving forward."',
      '"As you navigate through life, let your movements be as deliberate and graceful as a cat on a prowl—advance with purpose and poise."',
      '"Each step you take towards your goals should be as calculated and deliberate as a cat preparing to pounce—be patient and precise."',
    ],
  },
};
