export const pt = {
  translation: {
    onboardingTitle1: 'Sinta-se inspirado e meowtivado',
    onboardingTitle2: 'Persiga seus sonhos sempre',
    onboardingTitle3: 'Aproveite cada meowmento',
    onboardingButton: 'Começar',
    search: 'Buscar',
    favoritesEmptyListDescription:
      'Nenhuma citação favorita ainda. Salve algumas miau-spirações purr-feitas!',
    favorites: 'Favoritos',
    delete: 'Excluir',
    cancel: 'Cancelar',
    settings: 'Configurações',
    appearance: 'Aparência',
    language: 'Idioma',
    theme: 'Tema',
    soon: 'Em breve',
    data: 'Dados',
    clearData: 'Limpar Dados',
    about: 'Sobre',
    version: 'Versão',
    rateApp: 'Avaliar App',
    contact: 'Contato',
    clearDataConfirm:
      'Tem certeza? Isso excluirá todos os seus favoritos e redefinirá as citações diárias.',
    success: 'Sucesso',
    dataCleared: 'Dados foram limpos com sucesso',
    confirm: 'Confirmar',
    buyThemeTitle: '🐾 Novo Tema 🐾',
    buyThemeMessage: 'Pronto para liberar este tema meow-ravilhoso?',
    applyThemeTitle: 'Aplicar Tema?',
    applyThemeMessage: 'Quer aplicar este tema agora?',
    quotes: [
      '"Comece cada dia com um propósito e termine com um ronronar de satisfação."',
      '"A jornada para seus sonhos é como a soneca de um gato—tranquila, pacífica e cheia de saltos inesperados."',
      '"Seu tigre interior está esperando para saltar sobre suas metas. Deixe-o rugir hoje!"',
      '"A vida é como um novelo de lã, cheia de voltas e reviravoltas. Desenrole com curiosidade e graça."',
      '"Persiga seus sonhos como um gato persegue um laser—focado, brincalhão e imparável."',
      '"Cada desafio é um novo arranhador para afiar suas habilidades."',
      '"Mantenha-se positivo, mesmo quando o mundo parecer um pouco histérico."',
      '"No jogo da vida, seja o gato que sempre cai de pé."',
      '"A meowtivação é a chave para desbloquear a erva-dos-gatos do sucesso."',
      '"Enrosque-se com seus sonhos, mas não se esqueça de saltar em direção a eles também."',
      '"Aproveite cada oportunidade e não deixe o rato da dúvida escapar."',
      '"Seus bigodes de sabedoria crescem com cada experiência—use-os para navegar seu caminho."',
      '"Seja o gato curioso que nunca para de explorar novos horizontes."',
      '"Mesmo nos dias mais longos, lembre-se que cada pôr do sol traz a promessa de um novo amanhecer."',
      '"O coração de um gato está cheio de determinação e um toque de travessura—use ambos a seu favor."',
      '"Equilibre suas metas como um gato se equilibrando em uma cerca, com graça e determinação."',
      '"Não tenha medo de mostrar suas garras quando estiver lutando pelos seus sonhos."',
      '"Deixe seu miado ser ouvido em um mundo de sussurros."',
      '"A vida é uma série de sonecas e aventuras—abrace ambas."',
      '"Cada dia é uma nova chance de arranhar seu destino com criatividade e confiança."',
      '"Em cada bigode, encontre a coragem para perseguir seus sonhos."',
      '"Deixe o seu tigre interior miar e aproveitar as oportunidades."',
      '"A vida é uma escalada, mas cada passo é um salto gracioso."',
      '"Mantenha-se curioso, como um gato perseguindo um raio de luz."',
      '"Estique suas patas e alcance as estrelas."',
      '"Até mesmo uma soneca de gato pode recarregar seus sonhos."',
      '"Quando a vida fica difícil, ronrone através dos desafios."',
      '"Cada miado é um lembrete para se expressar."',
      '"Mantenha suas garras afiadas, seus objetivos mais afiados."',
      '"Como um gato, aterre-se de pé, não importa a queda."',
      '"Aproveite cada oportunidade com graça felina."',
      '"Encontre alegria nas coisas simples, como um gato com um raio de sol."',
      '"O caminho para o sucesso é uma série de saltos bem cronometrados."',
      '"Nos momentos de silêncio, deixe suas ideias criarem raízes."',
      '"Com cada ronronar, deixe ir o que não te serve."',
      '"A graça de um gato é igualada apenas pela sua determinação."',
      '"Persiga seus sonhos como um gato perseguindo um laser."',
      '"Seu potencial é tão vasto quanto a curiosidade de um gato."',
      '"Deixe que seus bigodes te guiem para novas aventuras."',
      '"Cada dia é uma chance de miar, esticar-se e crescer."',
      '"Cada desafio é apenas um rato a ser capturado, então não tenha medo de se lançar."',
      '"Um gato nunca se apressa, mas sempre chega ao seu destino com elegância e propósito."',
      '"Deixe seu espírito se elevar como um gato perseguindo uma borboleta em um dia de verão."',
      '"Diante da adversidade, lembre-se, até um pequeno gatinho tem o coração de um leão."',
      '"Ronroneie com satisfação, mas nunca pare de buscar seu próximo sonho."',
      '"O mundo é seu parque de diversões; pule sobre obstáculos como um gato perseguindo uma bola de lã."',
      '"Mesmo a soneca mais longa termina com um alongamento e uma nova aventura para explorar."',
      '"Encontre seu raio de sol e desfrute do calor de suas conquistas."',
      '"Cada dia é uma nova chance para afiar suas garras e refinar suas metas."',
      '"Não importa quão alta seja a escalada, lembre-se de que até a árvore mais alta começa no chão."',
      '"A graça de um gato não está apenas em seus passos, mas em sua capacidade de cair de pé, sempre."',
      '"Persiga seus sonhos com a mesma determinação que um gato usa para pegar sua presa."',
      '"Na quietude da noite, deixe seus sonhos vagarem livres como um gato à espreita."',
      '"O sucesso está a apenas uma série de pulos bem planejados de distância."',
      '"O mundo está cheio de cantos e fendas, todos esperando para serem explorados."',
      '"Como um gato, deixe a curiosidade ser o combustível que impulsiona sua jornada."',
      '"Nunca subestime o poder de um ronronar bem cronometrado; pode abrir portas para novas oportunidades."',
      '"Cada dia oferece uma nova aventura, então mergulhe nela com toda a graça de um felino."',
      '"Diante do fracasso, lembre-se: até um gato não pega o rato na primeira tentativa."',
      '"Cada movimento de bigode é um lembrete para estar atento ao seu entorno e aproveitar as oportunidades."',
      '"O caminho para o sucesso é como a caça de um gato: paciente, calculado e sempre preciso."',
      '"Não apenas suba árvores, busque alcançar o galho mais alto onde a vista é a melhor."',
      '"Os menores passos podem levar às maiores mudanças, assim como um gatinho cresce para se tornar um grande gato."',
      '"Deixe cada dia começar com um alongamento, um ronronar e um renovado sentido de propósito."',
      '"Seus objetivos podem ser altos, mas com determinação felina, nenhuma árvore é alta demais para escalar."',
      '"Em cada miado há uma história esperando para ser contada, então faça a sua valer a pena."',
      '"Mesmo nos dias mais preguiçosos, lembre-se de que o descanso é apenas a preparação para seu próximo grande salto."',
      '"Um gato não precisa de permissão para ser majestoso, e você também não."',
      '"Com cada novo amanhecer, lembre-se de que você tem nove vidas para realizar seus sonhos."',
      '"Mesmo quando o mundo parece caótico, encontre seu centro de calma e deixe-o guiá-lo."',
      '"Um suave ronronar pode transformar os dias mais difíceis em algo bonito."',
      '"O caminho para seus sonhos pode ser longo, mas cada passo é um salto para seu destino."',
      '"Nunca pare de brincar, pois no brincar encontramos o verdadeiro significado da alegria e criatividade."',
      '"A vida é melhor com um pouco de persuasão felina; use seu charme para abrir novas portas."',
      '"Nenhuma meta é grande demais se você abordá-la com a paciência e precisão de um gato."',
      '"Mesmo na noite mais escura, os olhos de um gato veem oportunidades onde outros não veem nada."',
      '"Com cada salto gracioso, lembre-se de que você está um passo mais perto de alcançar seus sonhos."',
      '"Deixe seu felino interior guiá-lo para os lugares onde seu coração realmente pertence."',
      '"Cada soneca de gato é um lembrete de que o descanso é tão importante quanto a ação."',
      '"Abrace sua independência, mas nunca esqueça o poder da conexão e da comunidade."',
      '"Como um gato em um raio de sol, encontre a luz em cada situação e aproveite-a."',
      '"Não apenas persiga seus sonhos; capture-os com a precisão de um gato à espreita de sua presa."',
      '"Deixe que sua curiosidade o leve a lugares que você nunca imaginou, assim como um gato explorando um novo mundo."',
      '"Com cada ronronar, deixe o passado para trás e receba o futuro de patas abertas."',
      '"Mesmo o gatinho mais pequeno tem o potencial de se tornar o rei da selva."',
      '"Encontre seu equilíbrio e mova-se pela vida com a graça de um felino."',
      '"Como um gato, seja tanto feroz quanto gentil; saiba quando se lançar e quando ronronar."',
      '"Cada dia é uma nova oportunidade para encontrar seu ritmo e dançar ao som do seu próprio tambor."',
      '"Cada desafio é uma nova oportunidade para mostrar sua força interior e resiliência."',
      '"A curiosidade de um gato nunca o supera; deixe que sua curiosidade guie seu caminho para o sucesso."',
      '"Cada salto que você dá é um passo mais perto de alcançar suas maiores aspirações."',
      '"Abrace o lado brincalhão da vida, pois no brincar descobrimos a essência da alegria."',
      '"Assim como um gato sempre cai de pé, você também encontrará seu caminho através de qualquer desafio."',
      '"Seus sonhos são tão vastos quanto o céu; deixe-os voar tão alto quanto um gato pula atrás de um pássaro."',
      '"Deixe cada ronronar ser um lembrete de que até os gestos menores podem trazer as maiores recompensas."',
      '"Cada momento de paciência é um passo em direção à grandeza, assim como um gato à espreita de sua presa."',
      '"Como um gato esperando o momento perfeito para pular, às vezes os melhores resultados vêm com o tempo."',
      '"Abrace sua jornada com a mesma elegância e graça que um gato demonstra em cada um de seus movimentos."',
      '"Deixe que seus sonhos sejam tão ilimitados quanto a imaginação de um gato enquanto persegue o invisível."',
      '"Cada dia é uma oportunidade para adicionar mais uma página à história do seu sucesso, então faça valer a pena."',
      '"Com cada suave ronronar, deixe para trás as dúvidas e abrace a certeza do seu potencial."',
      '"A natureza brincalhona de um gato nos lembra que o sucesso pode ser tanto sobre aproveitar a jornada quanto alcançar o objetivo."',
      '"Encontre seu propósito com o mesmo foco que um gato usa para seguir um ponto de laser; nunca perca de vista."',
      '"Cada passo que você dá é uma dança com o destino; que seja tão elegante quanto a pata de um gato."',
      '"Celebre cada pequena vitória como um gato celebra um novo brinquedo; é um passo em direção a um sucesso maior."',
      '"Deixe seu espírito ser tão inquebrantável quanto a determinação de um gato; com perseverança, tudo é possível."',
      '"Cada dia é uma nova aventura, então abrace-a com a mesma curiosidade que um gatinho explora um novo brinquedo."',
      '"Como um gato aconchegado ao sol, encontre seus momentos de paz em meio ao tumulto."',
      '"Não apenas sonhe com o sucesso; torne-o realidade com a persistência de um gato na caça."',
      '"Cada dia é uma oportunidade para explorar novos caminhos e alcançar novas alturas, assim como um gato explora seu mundo."',
      '"Com cada movimento gracioso, lembre-se de que você é capaz de realizar grandes coisas, assim como um gato."',
      '"Abrace sua jornada com a mesma confiança que um gato demonstra ao saltar de um telhado para outro."',
      '"Cada momento de descanso é uma preparação para o próximo salto em direção aos seus sonhos, assim como a pausa de um gato antes de um salto."',
      '"Deixe que suas metas sejam tão altas quanto os sonhos de um gato ao olhar pela janela; mire nas estrelas."',
      '"Em cada salto que você dá, encontre a alegria e o entusiasmo que um gato sente ao perseguir seu brinquedo favorito."',
      '"Deixe que o calor de suas conquistas seja como o local ensolarado de um gato; aproveite-o e valorize cada momento."',
      '"Abrace cada desafio com a mesma determinação que um gato demonstra ao seguir um ponto de laser."',
      '"Cada dia oferece um novo começo; acérquese a ele com a curiosidade e entusiasmo de um gatinho explorando um novo brinquedo."',
      '"Deixe que cada conquista seja um lembrete de que você é capaz de mais, assim como um gato fica mais forte com cada brincadeira."',
      '"Cada nova experiência é uma oportunidade para crescer, assim como um gato aprende e se adapta ao seu ambiente."',
      '"Celebre seu progresso com a mesma alegria que um gato demonstra ao capturar um novo brinquedo ou descobrir um novo canto."',
      '"Encontre seu ritmo e mova-se com a graça e confiança de um gato em missão."',
      '"Cada dia é uma nova oportunidade para perseguir seus sonhos com o mesmo entusiasmo que um gato tem por seu brinquedo favorito."',
      '"Deixe que suas metas brilhem tão intensamente quanto os olhos de um gato na escuridão; com foco, você pode realizar qualquer coisa."',
      '"Abrace sua força interior com a mesma elegância e determinação que um gato demonstra ao enfrentar um novo desafio."',
      '"Cada passo à frente é um salto em direção aos seus sonhos; que seja tão audacioso e decidido quanto o salto de um gato."',
      '"Celebre cada sucesso, por menor que seja, com a mesma alegria e entusiasmo que um gato tem por sua guloseima favorita."',
      '"Deixe sua jornada ser tão aventureira e emocionante quanto a exploração brincalhona de um gato em seu mundo."',
      '"Cada desafio que você enfrenta é como um ratinho esperando ser pego—avance com coragem e determinação."',
      '"Um gato pode não se apressar, mas sempre chega ao seu destino com uma mistura de graça e propósito—tome essa lição para o seu caminho."',
      '"Imagine seu espírito se elevando como um gato perseguindo uma borboleta na brisa quente de verão; deixe seus sonhos decolarem."',
      '"Mesmo diante dos obstáculos mais difíceis, lembre-se de que até o menor dos gatinhos tem o coração e a coragem de um leão."',
      '"Ronroneie satisfeito por suas conquistas, mas continue buscando seu próximo grande sonho com a mesma tenacidade."',
      '"A vida é seu playground—navegue pelos obstáculos com a agilidade brincalhona de um gato pulando atrás de um novelo de lã."',
      '"Até as sonecas mais longas e preguiçosas terminam com um alongamento e um renovado senso de aventura; certifique-se de rejuvenescer e continuar explorando."',
      '"Encontre seu raio de sol pessoal e aproveite o calor das suas conquistas, assim como um gato aproveita um lugar ensolarado."',
      '"Cada novo dia traz uma nova oportunidade para afiar suas garras e refinar seus objetivos—abrace o processo com entusiasmo."',
      '"Não importa quão alta pareça a escalada, lembre-se de que até a árvore mais alta começou do chão; seus esforços te levarão para cima."',
      '"A graça de um gato não está apenas em seus passos, mas em sua habilidade de cair de pé, independentemente da queda; aprenda com sua resiliência."',
      '"Persiga seus sonhos com a mesma determinação e foco que um gato usa quando está caçando sua presa—seja implacável."',
      '"Na quietude da noite, deixe seus sonhos vagarem livremente como um gato à procura de aventuras, explorando cada possibilidade."',
      '"O sucesso é como uma série de saltos bem planejados; cada passo que você dá te aproxima de alcançar suas metas."',
      '"O mundo está cheio de cantos e recantos escondidos esperando para ser descobertos—abrace sua curiosidade e explore tudo."',
      '"Deixe a curiosidade impulsionar sua jornada como faz para um gato explorando novos territórios; deixe-a levar você a descobertas maravilhosas."',
      '"Nunca subestime o poder de um ronronar bem cronometrado; pode transformar desafios em oportunidades e abrir portas que você não viu antes."',
      '"Cada dia oferece uma nova aventura, então mergulhe nela com a mesma graça e entusiasmo de um felino enquanto explora seu mundo."',
      '"Ao enfrentar fracassos, lembre-se: até um gato não pega sua presa na primeira tentativa; a persistência é a chave."',
      '"Cada movimento dos bigodes de um gato é um lembrete para se manter alerta e aproveitar as oportunidades ao seu redor com preparação e antecipação."',
      '"O caminho para o sucesso é como a caça de um gato: paciente, calculada e executada com precisão—mantenha o foco e a determinação."',
      '"Não se limite a escalar árvores; mire nas ramas mais altas onde a vista é a mais magnífica—estique suas ambições."',
      '"Os passos menores podem levar às mudanças mais significativas; como um gatinho crescendo em um gato majestoso, abrace sua jornada de crescimento."',
      '"Comece cada dia com um alongamento, um ronronar e um renovado senso de propósito—prepare-se para o que vem a seguir."',
      '"Seus objetivos podem parecer altos, mas com a determinação felina, nenhuma árvore é alta demais para conquistar—alcance as estrelas."',
      '"Cada miado conta uma história esperando para ser compartilhada; certifique-se de que sua história seja uma de perseverança e sucesso."',
      '"Mesmo nos dias mais preguiçosos, lembre-se de que o descanso é apenas a preparação para seu próximo grande salto em direção aos seus sonhos; recarregue e continue se movendo."',
      '"Um gato não precisa de permissão para ser majestoso, e você também não—abrace sua grandeza inerente e brilhe."',
      '"Com cada novo amanhecer, lembre-se de que você tem múltiplas chances para alcançar seus sonhos—como ter nove vidas, faça cada uma contar."',
      '"Mesmo quando o mundo ao seu redor parecer caótico, encontre seu centro de calma e deixe que ele te guie através da tempestade."',
      '"O ronronar suave pode transformar os dias mais difíceis em algo belo e reconfortante; deixe que ele te traga paz."',
      '"A jornada para seus sonhos pode ser longa, mas cada passo é um salto em direção aos seus objetivos; mantenha-se firme e persistente."',
      '"Nunca pare de brincar, pois no brincar descobrimos a verdadeira essência da alegria e da criatividade—mantenha o espírito brincalhão vivo em seus esforços."',
      '"A vida é melhor com um toque de charme felino; use suas qualidades únicas para abrir novas portas e oportunidades."',
      '"Nenhum objetivo é grande demais se abordado com a paciência e precisão de um gato; mantenha o foco metódico."',
      '"Mesmo nas noites mais escuras, os olhos de um gato encontram oportunidades onde outros só veem sombras; deixe que sua visão te guie."',
      '"Com cada salto elegante, lembre-se de que você está avançando em direção aos seus sonhos; continue se movendo com propósito e confiança."',
      '"Deixe que seu felino interior te guie para onde seu coração realmente pertence—siga seus instintos e paixões."',
      '"Cada soneca é um lembrete de que o descanso é essencial para o próximo salto em direção aos seus sonhos; equilibre a ação com momentos de relaxamento."',
      '"Abracce sua independência, mas também reconheça a força na comunidade e na conexão—cultive ambos."',
      '"Como um gato aconchegado em um raio de sol, encontre e aproveite a luz em cada situação; deixe que ela te aqueça e inspire."',
      '"Não apenas persiga seus sonhos—capture-os com a mesma precisão e dedicação que um gato mostra ao caçar sua presa."',
      '"Deixe que sua curiosidade te leve a novos horizontes, assim como um gato explora seu mundo com maravilha e emoção."',
      '"Com cada ronronar, libere o passado e acolha seu potencial—abrace suas capacidades com confiança."',
      '"Até o menor dos gatinhos tem o potencial de se tornar uma criatura majestosa—nunca subestime seu próprio potencial."',
      '"Encontre seu equilíbrio e navegue pela vida com a mesma graça que um felino demonstra—mova-se com propósito e elegância."',
      '"Como um gato, seja tanto feroz quanto gentil; entenda quando agir com decisão e quando mostrar paciência e compaixão."',
      '"Cada dia é uma nova oportunidade para encontrar seu ritmo e dançar ao compasso do seu próprio tambor—abrace sua jornada única."',
      '"Cada desafio que você enfrenta é uma nova oportunidade para demonstrar sua força e resiliência; enfrente cada ocasião com confiança."',
      '"A curiosidade de um gato nunca o limita; deixe que sua própria curiosidade guie seu caminho para o sucesso e a descoberta."',
      '"Cada salto que você dá te aproxima de alcançar suas aspirações mais altas; continue saltando com coragem e determinação."',
      '"Abracce o lado brincalhão da vida, pois no brincar encontramos a essência da alegria e da criatividade—nunca perca seu espírito brincalhão."',
      '"Assim como um gato sempre cai de pé, confie que você também encontrará seu caminho através de qualquer desafio com resiliência e adaptabilidade."',
      '"Seus sonhos são vastos como o céu; deixe-os voar tão alto quanto um gato salta atrás de um pássaro—alcance as estrelas."',
      '"Deixe que cada ronronar te lembre que mesmo as ações mais pequenas podem trazer grandes recompensas—valorize cada momento de progresso."',
      '"Cada momento de paciência é um passo em direção à grandeza; assim como um gato esperando o momento perfeito para pular—confie no processo."',
      '"Às vezes, os melhores resultados vêm com o tempo, assim como um gato espera o momento perfeito para pular—confie no processo."',
      '"Abracce sua jornada com a mesma elegância e graça que um gato demonstra em cada movimento—mova-se pela vida com postura."',
      '"Deixe seus sonhos serem tão ilimitados quanto a imaginação de um gato enquanto persegue o invisível—siga suas paixões com energia ilimitada."',
      '"Cada dia oferece uma oportunidade para adicionar uma nova página à sua história de sucesso—faça com que cada momento conte e escreva sua própria narrativa."',
      '"Com cada suave ronronar, libere as dúvidas e dê as boas-vindas ao seu potencial—abrace suas capacidades com confiança."',
      '"A natureza brincalhona de um gato nos lembra que o sucesso é sobre aproveitar a jornada tanto quanto alcançar o objetivo—encontre alegria em cada passo."',
      '"Encontre seu propósito com o mesmo foco que um gato tem em um laser—não perca de vista seus objetivos e ambições."',
      '"Cada passo que você dá é uma dança com o destino; que seja tão elegante e deliberado quanto os movimentos das patas de um gato."',
      '"Celebre cada pequena vitória como um gato com um novo brinquedo; é um passo em direção ao sucesso maior—desfrute de cada conquista."',
      '"Deixe que seu espírito seja tão inabalável quanto a determinação de um gato; com persistência, tudo é possível—continue avançando."',
      '"Cada dia é uma nova aventura—enfrente-a com a curiosidade e entusiasmo de um gatinho explorando um novo brinquedo."',
      '"Como um gato aconchegado em um raio de sol, encontre momentos de paz em meio ao caos da vida—aprecie a tranquilidade sempre que possível."',
      '"Não apenas sonhe com o sucesso—torná-lo realidade com a persistência e foco de um gato em busca de seu prêmio."',
      '"Cada dia apresenta uma oportunidade para explorar novos caminhos e alcançar novas alturas, assim como um gato explora seu mundo com entusiasmo."',
      '"Com cada movimento elegante, lembre-se de que você é capaz de realizar grandes coisas—seja tão poise e decidido quanto um gato."',
      '"Abracce sua jornada com a mesma confiança que um gato mostra ao saltar de um telhado para outro—sem medo e determinado."',
      '"Cada momento de descanso é uma preparação para o próximo salto em direção aos seus sonhos—equilibre seus esforços com momentos de rejuvenescimento."',
      '"Deixe que suas metas sejam tão altas quanto os sonhos de um gato ao olhar pela janela; mire nas estrelas e alcance suas aspirações."',
      '"Cada desafio que você supera é um testemunho da sua força e resiliência; deixe que seus sucessos te inspirem e motivem ainda mais."',
      '"Mova-se pela vida com a mesma elegância e confiança que um gato em seu domínio—afirme e mova-se com graça."',
      '"Assim como o ronronar de um gato pode acalmar, deixe que suas conquistas tragam paz e alegria—celebre seu progresso com orgulho."',
      '"Cada desafio que você enfrenta é como um rato esperando ser capturado—avance com coragem e determinação, assim como um gato na caça."',
      '"Um gato pode não correr, mas sempre chega ao destino com graça e propósito—tome essa lição para sua jornada."',
      '"Imagine sua mente se elevando como um gato caçando uma borboleta na brisa suave de verão; deixe seus sonhos voarem com a mesma alegria."',
      '"Mesmo nos momentos mais difíceis, lembre-se de que até o menor dos gatinhos tem o coração e a coragem de um leão."',
      '"Ronronar com satisfação por suas realizações, mas continue a buscar seu próximo grande sonho com a mesma tenacidade de antes."',
      '"A vida é seu playground—navegue pelos obstáculos com a agilidade lúdica de um gato pulando atrás de um novelo de lã."',
      '"Mesmo as sonecas mais longas e preguiçosas terminam com um alongamento e um sentimento renovado de aventura; certifique-se de se regenerar e continuar explorando."',
      '"Encontre seu raio de sol pessoal e descanse no calor de suas conquistas, assim como um gato encontra um lugar ensolarado para relaxar."',
      '"Cada novo dia traz uma oportunidade fresca para afiar suas garras e aprimorar seus objetivos—abrace o processo com entusiasmo."',
      '"Não importa quão alta a subida pareça, lembre-se de que até a árvore mais alta começou do chão—seus esforços o elevarão."',
      '"A graça de um gato não está apenas em seus passos, mas em sua capacidade de aterrissar sobre suas patas, não importa a queda—aprenda com sua resiliência."',
      '"Persiga seus sonhos com a mesma determinação e foco de um gato rastreando sua presa—seja inflexível em sua busca."',
      '"No silêncio da noite, deixe seus sonhos vagarem livremente como um gato buscando novas aventuras, explorando cada possibilidade."',
      '"O sucesso é como uma série de saltos bem planejados; cada passo que você dá o aproxima da realização de seus objetivos."',
      '"O mundo está cheio de cantos escondidos e fissuras esperando para serem descobertos—abrace sua curiosidade e explore tudo."',
      '"Deixe a curiosidade guiar sua jornada como um gato explorando novos territórios; deixe-a levar você a descobertas maravilhosas e novos horizontes."',
      '"Nunca subestime o poder de um ronronar bem cronometrado; ele pode transformar desafios em oportunidades e abrir portas que você não viu antes."',
      '"Cada dia traz uma nova aventura, então mergulhe com a mesma graça e entusiasmo de um felino explorando seu mundo."',
      '"Quando você enfrentar contratempos, lembre-se: até um gato não captura sua presa na primeira tentativa; a persistência é essencial."',
      '"Cada movimento dos bigodes de um gato é um lembrete para permanecer alerta e agarrar as oportunidades ao seu redor com preparação e antecipação."',
      '"O caminho para o sucesso é como uma caça de gato: paciente, calculada e executada com precisão—mantenha seu foco e determinação."',
      '"Não se contente apenas em subir nas árvores; mire nos galhos mais altos onde a vista é a mais magnífica—expanda suas ambições."',
      '"Pequenos passos podem levar a mudanças mais significativas; assim como um gatinho crescendo para se tornar um gato majestoso, abrace sua jornada de crescimento."',
      '"Comece cada dia com um alongamento, um ronronar e um senso renovado de propósito—prepare-se para o que vem a seguir."',
      '"Seus objetivos podem parecer altos, mas com a determinação felina, nenhuma árvore é alta demais para ser conquistada—alcance as estrelas."',
      '"Cada miado conta uma história esperando para ser compartilhada; certifique-se de que sua história seja uma de perseverança e sucesso."',
      '"Mesmo durante os dias mais preguiçosos, lembre-se de que o descanso é apenas uma preparação para seu próximo grande salto em direção aos seus sonhos; recupere-se e continue."',
      '"Um gato não precisa de permissão para ser majestoso, e você também não—abrace sua grandeza inerente e brilhe."',
      '"Com cada novo nascer do sol, lembre-se de que você tem várias chances de realizar seus sonhos—como ter nove vidas, faça com que cada uma conte."',
      '"Mesmo quando o mundo ao seu redor parece caótico, encontre seu centro de calma e deixe-o guiá-lo através da tempestade."',
      '"Um ronronar suave pode transformar os dias mais difíceis em algo bonito e reconfortante; deixe-o trazer paz para você."',
      '"A jornada em direção aos seus sonhos pode ser longa, mas cada etapa é um salto em direção aos seus objetivos; continue perseverando e determinado."',
      '"Nunca pare de brincar, pois no jogo descobrimos a verdadeira essência da alegria e da criatividade—mantenha seu espírito lúdico vivo em seus esforços."',
      '"A vida é melhor com um toque de charme felino; use suas qualidades únicas para abrir novas portas e oportunidades."',
      '"Nenhum objetivo é grande demais se for abordado com a paciência e a precisão de um gato; mantenha seu foco metódico."',
      '"Mesmo durante as noites mais escuras, os olhos de um gato encontram oportunidades onde outros veem apenas sombras—deixe sua visão guiá-lo."',
      '"Com cada salto gracioso, lembre-se de que você está se aproximando de seus sonhos—continue avançando com determinação e confiança."',
      '"Deixe seu felino interior guiá-lo para onde seu coração realmente pertence—siga seus instintos e suas paixões."',
      '"Cada soneca é um lembrete de que o descanso é essencial para o próximo salto em direção aos seus sonhos—equilibre seus esforços com momentos de relaxamento."',
      '"Abracem sua independência, mas também reconheçam a força na comunidade e na conexão—cultive ambos."',
      '"Como um gato enrolado em um raio de sol, encontre e aproveite a luz de cada situação; deixe-a aquecê-lo e inspirá-lo."',
      '"Não se contente apenas em perseguir seus sonhos—capture-os com a mesma precisão e dedicação de um gato rastreando sua presa."',
      '"Deixe a curiosidade guiá-lo para novos horizontes, como um gato explorando seu mundo com deslumbramento e entusiasmo."',
      '"Com cada ronronar, libere o passado e acolha seu potencial—aceite suas habilidades com confiança."',
      '"Mesmo o menor dos gatinhos tem o potencial de se tornar uma criatura majestosa—nunca subestime seu próprio potencial."',
      '"Encontre seu equilíbrio e avance na vida com a mesma graça que um felino—mova-se com propósito e elegância."',
      '"Seja feroz e gentil ao mesmo tempo, como um gato; entenda quando agir com decisão e quando mostrar paciência e compaixão."',
      '"Cada dia é uma nova oportunidade para encontrar seu ritmo e dançar ao som do seu próprio tambor—abrace sua jornada única."',
      '"Cada desafio que você supera é um testemunho de sua força e resiliência; deixe seus sucessos inspirá-lo e motivá-lo ainda mais."',
      '"Mova-se pela vida com a mesma graça e confiança que um gato mostra em seu domínio—afirme e avance com elegância."',
      '"Assim como um ronronar pode acalmar, deixe suas realizações trazerem paz e alegria—celebre seu progresso com orgulho."',
      '"Encare cada desafio com a graça e tenacidade de um gato em missão—sua persistência levará ao sucesso."',
      '"A cada salto que você der, lembre-se de que até um gato pausa para reunir forças antes do próximo pulo—equilibre seus esforços com paciência."',
      '"Deixe suas ambições alcançarem alturas grandiosas, como um gato caçando sua presa com foco e precisão inabaláveis—busque a grandeza."',
      '"Um dia dedicado a perseguir seus sonhos é como um gato explorando novos territórios; enfrente cada momento com curiosidade e determinação."',
      '"Descanse e recarregue energias como um gato, sabendo que cada pausa é uma preparação para o próximo grande salto em direção aos seus objetivos."',
      '"Até o menor esforço pode levar a resultados significativos; como um gatinho crescendo para se tornar um majestoso gato, acredite em seu potencial."',
      '"Comece cada dia com a confiança de um gato caminhando em direção a um raio de sol—abrace suas conquistas e enfrente novos desafios com a mesma elegância."',
      '"Transforme seus objetivos em realidade com a mesma precisão de um gato capturando uma borboleta—seja focado e implacável."',
      '"Com cada obstáculo que você supera, lembre-se de que até o gato mais ágil enfrenta desafios com paciência e graça—persista diante das dificuldades."',
      '"Em sua jornada para o sucesso, deixe sua curiosidade guiá-lo como um gato explorando um novo playground—descubra e cresça a cada passo."',
      '"Não importa o quão alto seja o desafio, saiba que cada esforço o aproxima mais de seus sonhos—como um gato escalando uma árvore alta, alcance o céu."',
      '"Deixe seu espírito ser tão brincalhão e livre quanto um gatinho; enfrente cada tarefa com entusiasmo e alegria, e você encontrará o sucesso a seguir."',
      '"Enfrente seus sonhos com a mesma coragem de um gato encarando seu reflexo; confie em suas habilidades e avance com confiança."',
      '"Mesmo nos momentos de descanso, seu progresso continua—como um gato aconchegado em um lugar confortável, deixe o descanso impulsionar seu próximo movimento."',
      '"Deixe cada desafio ser um degrau, como um gato pulando de um telhado para outro; cada salto o aproxima mais de suas metas."',
      '"Abrance sua jornada única com o mesmo orgulho de um gato exibindo seu belo pelo—celebre cada conquista e continue avançando."',
      '"À medida que você navega pela vida, deixe seus movimentos serem tão deliberados e elegantes quanto um gato em patrulha—avance com propósito e graça."',
      '"Cada passo em direção às suas metas deve ser tão calculado e deliberado quanto um gato se preparando para atacar—seja paciente e preciso."',
    ],
  },
};
